name: Run Python Tests

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.11", "3.12" ]

    steps:

    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install uv
        uv venv
        source .venv/bin/activate
        uv pip install ".[test]"
        uv pip install pytest

    - name: Run tests
      env:  
        SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      run: uv run pytest
